version: "3.8"

services:
  app-1:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: app-1
    environment:
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/rinha
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SERVER_PORT=9999
      - JAVA_TOOL_OPTIONS=-XX:+UseContainerSupport -XX:MaxRAMPercentage=80.0 -XX:+UseSerialGC -Xss512k
      - SPRING_MAIN_LAZY_INITIALIZATION=true
    networks:
      - backend
      - payment-processor
#    deploy:
#      resources:
#        limits:
#          cpus: "0.5"
#          memory: "610MB"

  app-2:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: app-2
    environment:
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/rinha
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SERVER_PORT=9999
      - JAVA_TOOL_OPTIONS=-XX:+UseContainerSupport -XX:MaxRAMPercentage=80.0 -XX:+UseSerialGC -Xss512k
      - SPRING_MAIN_LAZY_INITIALIZATION=true
    networks:
      - backend
      - payment-processor
#    deploy:
#      resources:
#        limits:
#          cpus: "0.5"
#          memory: "610MB"

  db:
    image: postgres:16
    hostname: db
    environment:
      POSTGRES_DB: rinha
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - backend
    volumes:
      - pgdata:/var/lib/postgresql/data
#    deploy:
#      resources:
#        limits:
#          cpus: "0.2"
#          memory: "95MB"

  load-balancer:
    image: nginx:latest
    hostname: load-balancer
    depends_on:
      - app-1
      - app-2
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - backend
#    deploy:
#      resources:
#        limits:
#          cpus: "0.15"
#          memory: "15MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true

volumes:
  pgdata:
