version: "3.8"

services:
  app-1:
    image: seu-usuario/rinha-backend:latest
    hostname: app-1
    environment:
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/rinha
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SERVER_PORT=9999
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "110MB"

  app-2:
    image: seu-usuario/rinha-backend:latest
    hostname: app-2
    environment:
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/rinha
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SERVER_PORT=9999
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "110MB"

  db:
    image: postgres:16
    hostname: db
    environment:
      POSTGRES_DB: rinha
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - backend
    volumes:
      - pgdata:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "95MB"

  load-balancer:
    image: nginx:latest
    hostname: load-balancer
    depends_on:
      - app-1
      - app-2
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "15MB"

  rabbitmq:
    image: rabbitmq:3.12-alpine
    hostname: rabbitmq
    networks:
      - backend
    ports:
      - "5672:5672"
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "20MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true

volumes:
  pgdata:
